apiVersion: v2
name: openwifi
appVersion: "1.0"
description: A Helm chart for Kubernetes
version: 0.1.0
dependencies:
- name: owgw
  repository: "git+https://github.com/Telecominfraproject/wlan-cloud-ucentralgw@helm?ref=master"
  version: 0.1.0
- name: owsec
  repository: "git+https://github.com/Telecominfraproject/wlan-cloud-ucentralsec@helm?ref=main"
  version: 0.1.0
- name: owfms
  repository: "git+https://github.com/Telecominfraproject/wlan-cloud-ucentralfms@helm?ref=main"
  version: 0.1.0
- name: owprov
  repository: "git+https://github.com/Telecominfraproject/wlan-cloud-owprov@helm?ref=main"
  version: 0.1.0
- name: owgwui
  repository: "git+https://github.com/Telecominfraproject/wlan-cloud-ucentralgw-ui@helm?ref=main"
  version: 0.1.0
- name: rttys
  repository: "git+https://github.com/Telecominfraproject/wlan-cloud-ucentralgw-rtty@chart?ref=main"
  version: 0.1.0
  condition: rttys.enabled
- name: kafka
  repository: https://charts.bitnami.com/bitnami
  version: 13.0.2
  condition: kafka.enabled
