# uCentralGW (https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/)
ucentralgw:

# rttys (https://github.com/Telecominfraproject/wlan-cloud-ucentralgw-rtty)
rttys:
  enabled: true
  config:
    token: 96181c567b4d0d98c50f127230068fa8

# kafka (https://github.com/bitnami/charts/blob/master/bitnami/kafka/)
kafka:
  enabled: true

  fullnameOverride: kafka

  image:
    registry: docker.io
    repository: bitnami/kafka
    tag: 2.8.0-debian-10-r43

  minBrokerId: 100

# uCentral UI (https://github.com/Telecominfraproject/wlan-cloud-ucentralgw-ui/)
ucentralgwui:
  enabled: true
