# OpenWIFI Gateway (https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/)
owgw:
  fullnameOverride: owgw

  configProperties:
    openwifi.kafka.enable: "true"
    openwifi.kafka.brokerlist: kafka:9092

# OpenWIFI Security (https://github.com/Telecominfraproject/wlan-cloud-ucentralsec)
owsec:
  fullnameOverride: owsec

  configProperties:
    openwifi.kafka.enable: "true"
    openwifi.kafka.brokerlist: kafka:9092

# OpenWIFI Firmware (https://github.com/Telecominfraproject/wlan-cloud-ucentralfms)
owfms:
  fullnameOverride: owfms

  configProperties:
    openwifi.kafka.enable: "true"
    openwifi.kafka.brokerlist: kafka:9092

# rttys (https://github.com/Telecominfraproject/wlan-cloud-ucentralgw-rtty)
rttys:
  enabled: true

  fullnameOverride: rttys

  config:
    token: 96181c567b4d0d98c50f127230068fa8

# kafka (https://github.com/bitnami/charts/blob/master/bitnami/kafka/)
kafka:
  enabled: true

  fullnameOverride: kafka

  image:
    registry: docker.io
    repository: bitnami/kafka
    tag: 2.8.0-debian-10-r43

  minBrokerId: 100

  zookeeper:
    fullnameOverride: zookeeper

# OpenWIFI Web UI (https://github.com/Telecominfraproject/wlan-cloud-ucentralgw-ui/)
owgwui:
  fullnameOverride: owgwui
