version: '3'

volumes:
  zookeeper_data:
    driver: local
  zookeeper_datalog:
    driver: local
  kafka_data:
    driver: local
  postgresql_data:
    driver: local

networks:
  owls:

services:
  owgw:
    image: "tip-tip-wlan-cloud-ucentral.jfrog.io/owgw:${OWGW_TAG}"
    networks:
      owls:
        aliases:
          - ${INTERNAL_OWGW_HOSTNAME}
    env_file:
      - ../owgw.env
    environment:
      - STORAGE_TYPE=postgresql
      - STORAGE_TYPE_POSTGRESQL_HOST=postgresql
    depends_on:
      - kafka
      - rttys
      - postgresql
    command: ["./wait-for-postgres.sh", "postgresql", "/openwifi/owgw"]
    restart: unless-stopped
    volumes:
      - "../owgw_data:${OWGW_ROOT}"
      - "../certs:/${OWGW_ROOT}/certs"
    ports:
      - "15002:15002"
      - "16002:16002"
      - "16102:16102"
      - "16003:16003"
    sysctls:
      - net.ipv4.tcp_keepalive_intvl=5
      - net.ipv4.tcp_keepalive_probes=2
      - net.ipv4.tcp_keepalive_time=45

  owgw-ui:
    image: "tip-tip-wlan-cloud-ucentral.jfrog.io/owgw-ui:${OWGWUI_TAG}"
    networks:
      owls:
    env_file:
      - ../owgw-ui.env
    depends_on:
      - owsec
      - owgw
      - owfms
      - owprov
    restart: unless-stopped
    volumes:
      - "../owgw-ui/default.conf:/etc/nginx/conf.d/default.conf"
      - "../certs/restapi-cert.pem:/etc/nginx/restapi-cert.pem"
      - "../certs/restapi-key.pem:/etc/nginx/restapi-key.pem"
    ports:
      - "80:80"
      - "443:443"

  owsec:
    image: "tip-tip-wlan-cloud-ucentral.jfrog.io/owsec:${OWSEC_TAG}"
    networks:
      owls:
        aliases:
          - ${INTERNAL_OWSEC_HOSTNAME}
    env_file:
      - owsec.env
    depends_on:
      - kafka
    restart: unless-stopped
    volumes:
      - "./owsec_data:${OWSEC_ROOT}"
      - "../certs:/${OWSEC_ROOT}/certs"
    ports:
      - "16001:16001"
      - "16101:16101"

  owfms:
    image: "tip-tip-wlan-cloud-ucentral.jfrog.io/owfms:${OWFMS_TAG}"
    networks:
      owls:
        aliases:
          - ${INTERNAL_OWFMS_HOSTNAME}
    env_file:
      - ../owfms.env
    depends_on:
      - kafka
    restart: unless-stopped
    volumes:
      - "../owfms_data:${OWFMS_ROOT}"
      - "../certs:/${OWFMS_ROOT}/certs"
    ports:
      - "16004:16004"
      - "16104:16104"

  owprov:
    image: "tip-tip-wlan-cloud-ucentral.jfrog.io/owprov:${OWPROV_TAG}"
    networks:
      owls:
        aliases:
          - ${INTERNAL_OWPROV_HOSTNAME}
    env_file:
      - ../owprov.env
    depends_on:
      - kafka
    restart: unless-stopped
    volumes:
      - "../owprov_data:${OWPROV_ROOT}"
      - "../certs:/${OWPROV_ROOT}/certs"
    ports:
      - "16005:16005"
      - "16105:16105"

  owprov-ui:
    image: "tip-tip-wlan-cloud-ucentral.jfrog.io/owprov-ui:${OWPROVUI_TAG}"
    networks:
      owls:
    env_file:
      - ../owprov-ui.env
    depends_on:
      - owsec
      - owgw
      - owfms
      - owprov
    restart: unless-stopped
    volumes:
      - "../owprov-ui/default.conf:/etc/nginx/conf.d/default.conf"
      - "../certs/restapi-cert.pem:/etc/nginx/restapi-cert.pem"
      - "../certs/restapi-key.pem:/etc/nginx/restapi-key.pem"
    ports:
      - "8080:8080"
      - "8443:8443"

  rttys:
    image: "tip-tip-wlan-cloud-ucentral.jfrog.io/rttys:${RTTYS_TAG}"
    restart: unless-stopped
    networks:
      owls:
    volumes:
      - "../certs/restapi-cert.pem:/etc/rttys/restapi-cert.pem"
      - "../certs/restapi-key.pem:/etc/rttys/restapi-key.pem"
      - "../rttys/rttys.conf:/rttys/rttys.conf"
    ports:
      - "5912:5912"
      - "5913:5913"

  owls:
    image: "tip-tip-wlan-cloud-ucentral.jfrog.io/owls:${OWLS_TAG}"
    networks:
      owls:
        aliases:
          - ${INTERNAL_OWLS_HOSTNAME}
    env_file:
      - owls.env
    depends_on:
      - owsec
      - kafka
    restart: unless-stopped
    volumes:
      - "./owls_data:${OWLS_ROOT}"
      - "../certs:/${OWLS_ROOT}/certs"
    ports:
      - "16007:16007"
      - "16107:16107"

  owls-ui:
    image: "tip-tip-wlan-cloud-ucentral.jfrog.io/owls-ui:${OWLSUI_TAG}"
    networks:
      owls:
    env_file:
      - owls-ui.env
    depends_on:
      - owsec
      - owls
    restart: unless-stopped
    volumes:
      - "./owls-ui/default.conf:/etc/nginx/conf.d/default.conf"
      - "../certs/restapi-cert.pem:/etc/nginx/restapi-cert.pem"
      - "../certs/restapi-key.pem:/etc/nginx/restapi-key.pem"
    ports:
      - "8081:80"
      - "8843:443"

  zookeeper:
    image: "zookeeper:${ZOOKEEPER_TAG}"
    networks:
      owls:
    restart: unless-stopped
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  kafka:
    image: "docker.io/bitnami/kafka:${KAFKA_TAG}"
    networks:
      owls:
    env_file:
      - kafka.env
    restart: unless-stopped
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka

  postgresql:
    image: "postgres:${POSTGRESQL_TAG}"
    networks:
      owls:
    env_file:
      - ../postgresql.env
    restart: unless-stopped
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ../postgresql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
