owgw:
  configProperties:
    storage.type: postgresql
    storage.type.postgresql.host: postgresql
    storage.type.postgresql.database: owgw
    storage.type.postgresql.username: owgw
    storage.type.postgresql.password: owgw

owsec:
  configProperties:
    storage.type: postgresql
    storage.type.postgresql.host: postgresql
    storage.type.postgresql.database: owsec
    storage.type.postgresql.username: owsec
    storage.type.postgresql.password: owsec

owfms:
  configProperties:
    storage.type: postgresql
    storage.type.postgresql.host: postgresql
    storage.type.postgresql.database: owfms
    storage.type.postgresql.username: owfms
    storage.type.postgresql.password: owfms

owprov:
  configProperties:
    storage.type: postgresql
    storage.type.postgresql.host: postgresql
    storage.type.postgresql.database: owprov
    storage.type.postgresql.username: owprov
    storage.type.postgresql.password: owprov

owanalytics:
  configProperties:
    storage.type: postgresql
    storage.type.postgresql.host: postgresql
    storage.type.postgresql.database: owanalytics
    storage.type.postgresql.username: owanalytics
    storage.type.postgresql.password: owanalytics

owsub:
  configProperties:
    storage.type: postgresql
    storage.type.postgresql.host: postgresql
    storage.type.postgresql.database: owsub
    storage.type.postgresql.username: owsub
    storage.type.postgresql.password: owsub

postgresql:
  initDbScriptSecret: enabled
  replicaCount: 1
  maxConnections: 453
  sharedBuffers: 128MB
  password: postgres
  postgresPassword: postgres
  repmgrPassword: postgres
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  initdbScripts:
    init.sql: | # <-- Here
      CREATE USER owgw WITH PASSWORD 'owgw';
      CREATE DATABASE owgw;
      GRANT ALL PRIVILEGES ON DATABASE owgw TO owgw;

  resources:
    requests:
      cpu: 250m
      memory: 1024Mi
    limits:
      cpu: 250m
      memory: 1024Mi
