name: CI

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  trigger-testing:
    if: startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    steps:
    - name: Get base branch name and set as output
      id: get_base_branch
      run: |
        echo ::set-output name=branch::$(echo ${GITHUB_BASE_REF##*/})
        echo ::set-output name=owgw_branch::$(echo ${GITHUB_BASE_REF##*/} | sed 's/main/master/g')

    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/.github
        path: github

    - name: Trigger testing of OpenWifi Docker Compose deployment and wait for result
      uses: ./github/composite-actions/trigger-workflow-and-wait
      env:
        BASE_BRANCH: ${{ steps.get_base_branch.outputs.branch }}
        OWGW_BASE_BRANCH: ${{ steps.get_base_branch.outputs.owgw_branch }}
      with:
        owner: Telecominfraproject
        repo: wlan-testing
        workflow: ow_docker-compose.yml
        token: ${{ secrets.WLAN_TESTING_PAT }}
        ref: master
        inputs: '{"microservice": "all", "deployment_version": "${{ github.sha }}", "owgw_version": "${{ env.OWGW_BASE_BRANCH }}", "owgwui_version": "${{ env.BASE_BRANCH }}", "owsec_version": "${{ env.BASE_BRANCH }}", "owfms_version": "${{ env.BASE_BRANCH }}", "owprov_version": "${{ env.BASE_BRANCH }}", "owprovui_version": "${{ env.BASE_BRANCH }}"}'
