name: CI

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  envs:
    name: Setup environment variables for further tests
    if: startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.get_base_branch.outputs.branch }}
      owgw_branch: ${{ steps.get_base_branch.outputs.owgw_branch }}
      pr_branch: ${{ steps.get_base_branch.outputs.pr_branch }}
    steps:
    - name: Get base branch name and set as output
      id: get_base_branch
      run: |
        echo ::set-output name=branch::$(echo ${GITHUB_BASE_REF##*/})
        echo ::set-output name=owgw_branch::$(echo ${GITHUB_BASE_REF##*/} | sed 's/main/master/g')
        echo ::set-output name=pr_branch::$(echo ${GITHUB_HEAD_REF})

  trigger-docker-compose-testing:
    if: startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    needs: envs
    steps:
    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/.github
        path: github

    - name: Trigger testing of OpenWifi Docker Compose deployment and wait for result
      uses: ./github/composite-actions/trigger-workflow-and-wait
      env:
        BASE_BRANCH: ${{ needs.envs.outputs.branch }}
        OWGW_BASE_BRANCH: ${{ needs.envs.outputs.owgw_branch }}
        PR_BRANCH: ${{ needs.envs.outputs.pr_branch }}
      with:
        owner: Telecominfraproject
        repo: wlan-testing
        workflow: ow_docker-compose.yml
        token: ${{ secrets.WLAN_TESTING_PAT }}
        ref: master
        inputs: '{"deployment_version": "${{ env.PR_BRANCH }}", "owgw_version": "${{ env.OWGW_BASE_BRANCH }}", "owsec_version": "${{ env.BASE_BRANCH }}", "owfms_version": "${{ env.BASE_BRANCH }}", "owprov_version": "${{ env.BASE_BRANCH }}", "owanalytics_version": "${{ env.BASE_BRANCH }}", "owsub_version": "${{ env.BASE_BRANCH }}", "microservice": "all"}'

  trigger-k8s-testing:
    if: startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    needs: envs
    steps:
    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/.github
        path: github

    - name: Trigger testing of OpenWifi Docker Compose deployment and wait for result
      uses: ./github/composite-actions/trigger-workflow-and-wait
      env:
        BASE_BRANCH: ${{ needs.envs.outputs.branch }}
        OWGW_BASE_BRANCH: ${{ needs.envs.outputs.owgw_branch }}
        PR_BRANCH: ${{ needs.envs.outputs.pr_branch }}
      with:
        owner: Telecominfraproject
        repo: wlan-testing
        workflow: ow_k8s.yml
        token: ${{ secrets.WLAN_TESTING_PAT }}
        ref: master
        inputs: '{"deployment_version": "${{ env.PR_BRANCH }}", "owgw_version": "${{ env.OWGW_BASE_BRANCH }}", "owsec_version": "${{ env.BASE_BRANCH }}", "owfms_version": "${{ env.BASE_BRANCH }}", "owprov_version": "${{ env.BASE_BRANCH }}", "owanalytics_version": "${{ env.BASE_BRANCH }}", "owsub_version": "${{ env.BASE_BRANCH }}", "microservice": "all"}'
